### ISSUE TITLE
Add support for code blocks

### ISSUE THREAD

**Issue by MaluNoPeleke** [johannschopplich/kirby-highlighter#10]
Is it possible to activate it for [code blocks](https://getkirby.com/docs/reference/panel/blocks/code) as well?

**Comment by johannschopplich** [comment]
Great idea! Done: https://github.com/johannschopplich/kirby-highlighter/releases/tag/v2.0.0

**Comment by MaluNoPeleke** [comment]
Wow, that was super quick, thanks a lot!

**Comment by johannschopplich** [comment]
You're welcome! I had some spare time coincidentally. 😉 Feel welcome to give feedback if something doesn't work.

**Comment by MaluNoPeleke** [comment]
I just tested it and it works flawlessly as excpected. 👍 
Is there an option to copy the whole code block to the clipboard?

**Comment by johannschopplich** [comment]
Glad to hear.

That you will have to implement yourself, as it's much more dependent on the architecture/styling of your website.

**Comment by johannschopplich** [comment]
@MaluNoPeleke Just thought of you, when I found: https://github.com/github/clipboard-copy-element

Pretty simple and maybe interesting to you!

**Comment by MaluNoPeleke** [comment]
Thanks a lot

**Comment by MaluNoPeleke** [comment]
Now I only need to find out how to inject it correctly ;)
