### ISSUE TITLE
Plugin mangles characters like `➜` and `▕`

### ISSUE THREAD

**Issue by miragecraft** [johannschopplich/kirby-highlighter#19]
The characters ➜ and▕ are mangled when plugin is active  as `âžœ` and `â–•`.

Other characters possibly affected, those are just the ones I've encountered.

**Comment by johannschopplich** [comment]
Hi there! 
Thanks for the bug report. I'm not actively developing this plugin anymore. PR gladly appreciated. 🙂

**Comment by miragecraft** [comment]
I understand, you might want to change the readme to reflect that or mark the repo as archived.

Since the PHP port of `highlight.js` this plugin relies upon is quite outdated (ex. missing support for new CSS syntaxes and at-rules), it doesn't seem like it's worth it to throw good development effort after the bad.

**Comment by johannschopplich** [comment]
Should be fixed by https://github.com/johannschopplich/kirby-highlighter/commit/0e4404da1a324d2a26d14c9f4e37c294b5416014.
