### ISSUE TITLE
Error when enabling autodetect

### ISSUE THREAD

**Issue by ro-ka** [johannschopplich/kirby-highlighter#2]
Somehow this appears. Most of my code blocks are explicit, it works then. Any idea on why this crashes? I have multiple code blocks in post.

![Bildschirmfoto vom 2020-07-26 um 16 31 44](https://user-images.githubusercontent.com/840022/88481817-ed65c780-cf5d-11ea-983b-42cd9562aa4e.png)

**Comment by johannschopplich** [comment]
See note in #3.
