### ISSUE TITLE
readme doesn't explain how to use included stylesheets

### ISSUE THREAD

**Issue by Splendorr** [johannschopplich/kirby-highlighter#5]
I really appreciate this plugin! But I was only able to get it work by moving a stylesheet into my standard assets folder. It would be good to include an example of how to link to a css file in the plugin folder! Thank you for your work either way!

**Comment by johannschopplich** [comment]
Thanks for the suggestion. I've added a styling section in my last commits: https://github.com/johannschopplich/kirby-highlighter/commit/b78e22b45f4152d73475c8ec33bd837bdde13a3a & https://github.com/johannschopplich/kirby-highlighter/commit/fb16a8c96e4b14bc2b71102d1a544a6bbdcc5355
